import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // SHARED / GLOBAL STYLES
  safeArea: {
    flex: 1,
    backgroundColor: '#F2F2F7',
  },
  globalContainer: {
    flex: 1,
    backgroundColor: '#F2F2F7',
  },
  centered: {
    padding: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // AUTH STYLES (Login, Signup)
  authContainer: {
    flex: 1,
    justifyContent: 'center',
    maxWidth: 500,
    width: '100%',
    alignSelf: 'center',
    padding: 16,
  },
  authCardSection: {
    backgroundColor: '#FFF',
    padding: 30,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  authMainTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  authSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  authInputRow: {
    flexDirection: 'column',
    marginBottom: 16,
  },
  authInputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3A3A3C',
    marginBottom: 8,
  },
  authInput: {
    height: 48,
    borderWidth: 1,
    borderColor: '#D1D1D6',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    backgroundColor: '#FAFAFA',
  },
  authActionBtn: {
    backgroundColor: '#007AFF',
    height: 50,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  authActionBtnSignup: {
    backgroundColor: '#34C759',
    height: 50,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  authBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  authSwitchBtn: {
    marginTop: 20,
    alignItems: 'center',
  },
  authSwitchText: {
    color: '#666',
    fontSize: 14,
  },
  authSwitchTextBold: {
    color: '#007AFF',
    fontWeight: 'bold',
  },
  authSwitchTextBoldSignup: {
    color: '#34C759',
    fontWeight: 'bold',
  },
  authRoleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  authRoleTab: {
    flex: 1,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: '#D1D1D6',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#FAFAFA',
  },
  authRoleTabActive: {
    backgroundColor: '#007AFF',
    borderColor: '#007AFF',
  },
  authRoleText: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
  },
  authRoleTextActive: {
    color: '#FFF',
    fontWeight: 'bold',
  },
  // DASHBOARD STYLES (Admin, Manager)
  dashContainer: {
    flex: 1,
    backgroundColor: '#F2F2F7',
    padding: 16,
  },
  dashSearchWrapper: {
    width: '100%',
    maxWidth: 600,
    marginBottom: 20,
  },
  dashSearchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    paddingHorizontal: 15,
    height: 50,
    borderRadius: 15,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
  },
  dashSearchInput: {
    flex: 1,
    marginLeft: 10,
    fontSize: 15,
    color: '#000',
  },
  dashGridCard: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 900,
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 4 },
  },
  dashCardHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 5,
    textAlign: 'center',
  },
  dashCardSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    textAlign: 'center',
    marginBottom: 20,
  },
  dashTable: {
    borderWidth: 1,
    borderColor: '#F0F0F0',
    borderRadius: 12,
    overflow: 'hidden',
  },
  dashTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  dashTableHeader: {
    backgroundColor: '#F9FAFB',
    borderBottomWidth: 2,
    borderBottomColor: '#EBEBEB',
    paddingVertical: 15,
  },
  dashRowAlt: {
    backgroundColor: '#FAFAFA',
  },
  dashHeaderCell: {
    fontSize: 12,
    fontWeight: '800',
    color: '#8E8E93',
    textAlign: 'center',
  },
  dashCell: {
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
    paddingHorizontal: 5,
  },
  dashRoleBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  dashManagerBadge: {
    backgroundColor: '#E8F5E9',
  },
  dashAdminBadge: {
    backgroundColor: '#FFF3E0',
  },
  dashUserBadge: {
    backgroundColor: '#E3F2FD',
  },
  dashRoleText: {
    fontSize: 10,
    fontWeight: '900',
    color: '#000',
  },
  dashSaveBtn: {
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
    elevation: 5,
    shadowOpacity: 0.4,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  dashSaveBtnText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 1,
  },
  dashNoResults: {
    padding: 30,
    alignItems: 'center',
  },
  dashNoResultsText: {
    color: '#8E8E93',
    fontSize: 14,
  },
  // CRUD TEMPLATE STYLES
  crudFlatListContent: {
    padding: 16,
    paddingBottom: 40,
  },
  crudHeaderContent: {
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
  },
  crudFooterContent: {
    width: '100%',
    maxWidth: 800,
    alignSelf: 'center',
  },
  crudMainTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    color: '#1C1C1E',
  },
  crudCardSection: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 16,
    elevation: 3,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  crudSectionHeaderCentered: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    color: '#007AFF',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  crudTableSubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 15,
  },
  crudInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  crudInputLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#3A3A3C',
    width: 90,
  },
  crudInput: {
    flex: 1,
    height: 44,
    borderWidth: 1,
    borderColor: '#D1D1D6',
    borderRadius: 8,
    paddingHorizontal: 12,
    fontSize: 16,
    backgroundColor: '#FAFAFA',
  },
  crudAddBtn: {
    backgroundColor: '#34C759',
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  crudActionBtn: {
    height: 48,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  crudAddBtnText: {
    color: '#FFF',
    fontWeight: 'bold',
    fontSize: 16,
  },
  crudEmptyText: {
    textAlign: 'center',
    color: '#8E8E93',
    fontSize: 16,
    padding: 10,
  },
  crudTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#007AFF',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  crudTableHeaderCellNo: {
    width: 50,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontSize: 15,
  },
  crudTableHeaderCellName: {
    flex: 1,
    fontWeight: 'bold',
    color: '#FFFFFF',
    fontSize: 15,
  },
  crudTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    paddingVertical: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    backgroundColor: '#FFF',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 800,
  },
  crudTableCellNo: {
    width: 50,
    color: '#333333',
    fontSize: 15,
    fontWeight: '500',
  },
  crudTableCellName: {
    flex: 1,
    color: '#333333',
    fontSize: 15,
    fontWeight: '500',
  },
  crudRestrictedContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    backgroundColor: '#F2F2F7',
  },
  crudRestrictedTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginTop: 20,
    marginBottom: 8,
  },
  crudRestrictedSubtitle: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 22,
  },
  // INDEX/APP STYLES
  indexLoadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F2F2F7',
  },
  indexHeader: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#EAEAEA',
    justifyContent: 'space-between',
  },
  indexHeaderLeft: {
    flex: 1,
  },
  indexHeaderRight: {
    flex: 1,
    alignItems: 'flex-end',
  },
  indexHeaderEmail: {
    fontSize: 12,
    fontWeight: '500',
    color: '#333',
  },
  indexHeaderRole: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#8E8E93',
  },
  indexIconBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#FFF5F5',
  },
  indexScreenPickerContainer: {
    backgroundColor: '#FFF',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F2F2F7',
  },
  indexScreenPicker: {
    paddingHorizontal: 16,
    gap: 10,
  },
  indexScreenPill: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    backgroundColor: '#F2F2F7',
  },
  indexScreenPillActive: {
    backgroundColor: '#007AFF',
  },
  indexScreenPillText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#8E8E93',
  },
  indexWhiteText: {
    color: '#FFF',
  },
  // PROFILE STYLES
  profileContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F2F2F7',
    alignItems: 'center',
  },
  profileCard: {
    backgroundColor: '#FFF',
    padding: 30,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    width: '100%',
    maxWidth: 500,
    marginTop: 20,
  },
  profileMainTitle: {
    fontSize: 26,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#1C1C1E',
    marginBottom: 8,
  },
  profileSubtitle: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    marginBottom: 24,
  },
  deleteBtn: {
    padding: 8,
    borderRadius: 6,
    backgroundColor: '#FFF5F5',
  },
  // DRAWER NAVIGATION STYLES
  drawerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1000,
  },
  drawerContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 280,
    backgroundColor: '#FFF',
    zIndex: 1001,
    elevation: 20,
    shadowColor: '#000',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 5, height: 0 },
    flexDirection: 'column',
  },
  drawerHeaderBlock: {
    paddingTop: 60,
    paddingBottom: 30,
    paddingHorizontal: 20,
    backgroundColor: '#F2F2F7',
    borderBottomWidth: 1,
    borderBottomColor: '#EAEAEA',
  },
  drawerHeaderEmail: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1C1C1E',
    marginBottom: 5,
  },
  drawerHeaderRole: {
    fontSize: 12,
    fontWeight: '800',
    color: '#007AFF',
    letterSpacing: 1,
  },
  drawerScrollArea: {
    flex: 1,
    paddingVertical: 10,
  },
  drawerMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  drawerMenuItemActive: {
    backgroundColor: '#E3F2FD',
    borderRightWidth: 4,
    borderRightColor: '#007AFF',
  },
  drawerMenuIcon: {
    marginRight: 15,
  },
  drawerMenuText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
  },
  drawerMenuTextActive: {
    color: '#007AFF',
    fontWeight: 'bold',
  },
  drawerFooter: {
    borderTopWidth: 1,
    borderTopColor: '#EAEAEA',
    paddingVertical: 10,
    paddingBottom: 30,
    backgroundColor: '#FAFAFA',
  },
});

export default styles;
